# Generated by Django 4.2.23 on 2025-08-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('html_score', models.IntegerField(default=0)),
                ('css_score', models.IntegerField(default=0)),
                ('javascript_score', models.IntegerField(default=0)),
                ('python_score', models.IntegerField(default=0)),
            ],
        ),
    ]
